Postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "root"
  DBName: "postgres"
  sslMode: "disable"
  pgDriver: "pgx"

Server:
  appVersion: "1.0.0"
  host: "0.0.0.0"
  port: "8080"
  timeout: 4s
  idle_timeout: "60s"
  environment: "local"
